language: python
sudo: false

env:
  - LUA="lua=5.1" LUA_PATH="tests/?;tests/?.lua;;"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install bitlib
  - luarocks install luaunit
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - lua -lluacov tests/TestAPI.lua -v
  - lua -lluacov tests/TestUtility.lua -v
  - lua -lluacov tests/TestSettings.lua -v
  - lua -lluacov tests/TestSystemEventHandler.lua -v

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
