name: CI

on:
  push:
    branches:
    - main
    - "release/**"
    - "feature/**"
  pull_request:
    branches:
    - main
    - "release/**"

  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          luaVersion: 5.1

        - os: macos-latest
          luaVersion: 5.1

        - os: windows-latest
          luaVersion: 5.1

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: setup msvc dev cmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: setup lua
      uses: luarocks/gh-actions-lua@v13
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: show lua version
      run: lua -v

    - name: install luarocks
      uses: luarocks/gh-actions-luarocks@v6

    - name: install dependencies
      run: |
        luarocks install bitlib
        luarocks install datafile
        luarocks install luaunit
        luarocks install luacov
        luarocks list

    - name: update luarocks paths
      run: luarocks path --no-bin >> $GITHUB_ENV

    - name: run tests
      env:
        LUA_PATH: "${{ env.LUA_PATH }};./tests/?.lua"
      run: |
        lua -lluacov tests/TestAPI.lua -v
        lua -lluacov tests/TestConfig.lua -v
        lua -lluacov tests/TestHoldDown.lua -v
        lua -lluacov tests/TestSettings.lua -v
        lua -lluacov tests/TestSystemEventHandler.lua -v
        lua -lluacov tests/TestUtility.lua -v
